# name: Deploy to VPS

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USERNAME }}
#           key: ${{ secrets.VPS_SSH_KEY }}
#           script: |
#             cd /www/wwwroot/kotkoti-backend

#             if [ -d ".git" ]; then
#               git pull origin main
#             else
#               git clone https://github.com/nexroxdigital/Kotkoti-backend.git .
#             fi

#             npm install
#             npm run build

#             pm2 restart kotkoti-backend || pm2 start dist/main.js --name kotkoti-backend
#             pm2 save
